const DATA_URL='data/engineer-method-v3.json';
const PROJECT_KEY='engineer-method-os-project-v3';
const MASTERY_KEY='engineer-method-os-mastery-v3';
let DATA=null;let selectedCompetency='software-engineering';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function getMastery(){try{return JSON.parse(localStorage.getItem(MASTERY_KEY))||{}}catch{return{}}}
function saveMastery(v){localStorage.setItem(MASTERY_KEY,JSON.stringify(v))}
function stateFor(id){const m=getMastery();return m[id]||{knowledge:0,coding:0,acceptance:0,quality:0,explanation:0,evidence:''}}
function scoreFor(s){const w=DATA.mastery_formula;return Math.round((s.knowledge*w.knowledge+s.coding*w.coding+s.acceptance*w.acceptance+s.quality*w.quality+s.explanation*w.explanation)/100)}
function levelFor(score,evidence){if(!score&&!evidence)return DATA.mastery_levels[0];if(score>=90&&evidence)return DATA.mastery_levels[5];if(score>=80)return DATA.mastery_levels[4];if(score>=65)return DATA.mastery_levels[3];if(score>=50)return DATA.mastery_levels[2];return DATA.mastery_levels[1]}
function verifiedEvidenceCount(){return Object.values(getMastery()).filter(v=>v.evidence&&v.evidence.trim()).length}
function globalScore(){const m=getMastery();return Math.round(DATA.competencies.reduce((a,c)=>a+scoreFor(m[c.id]||stateFor(c.id)),0)/DATA.competencies.length)}
function setupTabs(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')}))}
function renderStats(){const s=DATA.stats;const cards=[['4','certificats IBM terminés'],[String(s.course_occurrences),'occurrences de cours'],['≈'+s.unique_courses_approx,'cours distincts normalisés'],[String(s.competency_blocks),'blocs de compétences']];$('statCards').innerHTML=cards.map(([n,l])=>`<article class="panel stat-card"><strong>${n}</strong><span>${l}</span></article>`).join('')}
function renderRoadmap(){const m=getMastery();$('roadmap').innerHTML=DATA.competencies.map(c=>{const sc=scoreFor(m[c.id]||stateFor(c.id));const lv=levelFor(sc,(m[c.id]||{}).evidence);return `<article class="road-item"><span class="n">${c.order}</span><h3>${esc(c.name)}</h3><p>${lv.label} · ${sc}%</p></article>`}).join('')}
function renderGlobal(){const s=globalScore();$('globalScore').textContent=s+'%';$('globalMeter').style.width=s+'%';const m=getMastery();const next=DATA.competencies.find(c=>scoreFor(m[c.id]||stateFor(c.id))<65)||DATA.competencies[0];$('nextRecommendation').innerHTML=`<h3>${esc(next.name)}</h3><p class="lead">Travaille ce bloc jusqu'à pouvoir l'expliquer puis produire une petite preuve. <strong>Preuve attendue :</strong> ${esc(next.proof)}</p><button class="primary-button" id="goMastery">Évaluer ce bloc</button><p class="muted">Preuves enregistrées actuellement : ${verifiedEvidenceCount()} / ${DATA.competencies.length}</p>`;$('goMastery').onclick=()=>{selectedCompetency=next.id;document.querySelector('[data-view="mastery"]').click();renderMastery()}}
function renderCertificates(){$('certificateGrid').innerHTML=DATA.certificates.map(c=>`<article class="cert-card"><span class="kicker">${c.course_count} COURS</span><h3>${esc(c.name)}</h3><p class="muted">Terminé le ${esc(c.completed)}</p><p>${esc(c.focus)}</p><div class="cert-meta"><span class="pill">Contribution unique</span></div><p><strong>${esc(c.unique)}</strong></p><details><summary>Voir les ${c.course_count} cours</summary><ol class="course-list">${c.courses.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details></article>`).join('')}
function renderSimilarity(){$('similarityGrid').innerHTML=DATA.similarity.map(x=>`<article class="similarity-card"><span class="shared">${x.shared}/4 certificats</span><strong>${esc(x.name)}</strong><p>${esc(x.why)}</p></article>`).join('')}
function renderSpecialties(){$('specialtyGrid').innerHTML=DATA.differentiation.map(x=>`<article class="specialty-card"><span class="kicker">SPÉCIALITÉ</span><h3>${esc(x.certificate)}</h3><ul>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></article>`).join('')}
function renderMasteryList(){const m=getMastery();$('competencyList').innerHTML=DATA.competencies.map(c=>{const s=scoreFor(m[c.id]||stateFor(c.id));return `<button class="competency-button ${c.id===selectedCompetency?'active':''}" data-id="${c.id}"><span>Bloc ${c.order} · ${s}%</span><strong>${esc(c.name)}</strong></button>`}).join('');document.querySelectorAll('.competency-button').forEach(b=>b.onclick=()=>{selectedCompetency=b.dataset.id;renderMastery()})}
function renderMastery(){renderMasteryList();const c=DATA.competencies.find(x=>x.id===selectedCompetency)||DATA.competencies[0];const s=stateFor(c.id),score=scoreFor(s),level=levelFor(score,s.evidence);$('masteryDetail').innerHTML=`<span class="kicker">BLOC ${c.order}</span><h2>${esc(c.name)}</h2><p class="muted">Certificats : ${c.certificates.map(esc).join(' · ')}</p><div class="concept-tags">${c.concepts.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="score-box"><div><div class="score-number">${score}%</div><strong>${esc(level.label)}</strong></div><div><div class="meter"><span style="width:${score}%"></span></div><p class="muted">Indice provisoire pondéré. Le niveau 5 exige aussi une preuve enregistrée.</p></div></div>${dimension('knowledge','Compréhension / quiz',s.knowledge,15)}${dimension('coding','Exercice de code',s.coding,30)}${dimension('acceptance','Résultat utilisateur / acceptance test',s.acceptance,25)}${dimension('quality','Tests, qualité, sécurité',s.quality,20)}${dimension('explanation','Explication avec mes mots',s.explanation,10)}<div class="proof-box"><strong>Preuve attendue</strong><p>${esc(c.proof)}</p><label>Lien ou note de preuve<input id="evidenceInput" value="${esc(s.evidence||'')}" placeholder="Ex. lien GitHub, PR, commit, test ou explication"></label></div><button id="saveMastery" class="primary-button wide">Enregistrer l'évaluation</button><p class="muted">Un certificat terminé signifie « étudié ». La maîtrise augmente seulement avec application, tests, correction et preuve.</p>`;['knowledge','coding','acceptance','quality','explanation'].forEach(k=>{const input=$('dim_'+k),out=$('out_'+k);input.oninput=()=>out.textContent=input.value+'%'});$('saveMastery').onclick=()=>{const m=getMastery();m[c.id]={knowledge:+$('dim_knowledge').value,coding:+$('dim_coding').value,acceptance:+$('dim_acceptance').value,quality:+$('dim_quality').value,explanation:+$('dim_explanation').value,evidence:$('evidenceInput').value.trim()};saveMastery(m);renderMastery();renderRoadmap();renderGlobal()}}
function dimension(id,label,value,weight){return `<div class="dimension"><div class="dimension-head"><span>${label} · poids ${weight}%</span><strong id="out_${id}">${value}%</strong></div><input id="dim_${id}" type="range" min="0" max="100" step="5" value="${value}"></div>`}
const projectFields={name:()=>$('projectName'),problem:()=>$('projectProblem'),users:()=>$('projectUsers'),mvp:()=>$('projectMvp'),currentStep:()=>$('projectStep')};
function getProject(){return Object.fromEntries(Object.entries(projectFields).map(([k,f])=>[k,f().value.trim()]))}
function setProject(p={}){Object.entries(projectFields).forEach(([k,f])=>{if(typeof p[k]==='string')f().value=p[k]})}
function saveProject(){localStorage.setItem(PROJECT_KEY,JSON.stringify(getProject()));$('saveState').textContent='Enregistré';setTimeout(()=>$('saveState').textContent='Mémoire locale',1200)}
function loadProject(){try{const p=JSON.parse(localStorage.getItem(PROJECT_KEY));if(p)setProject(p)}catch{}}
function setStage(stage){document.querySelectorAll('.pipeline-step').forEach(x=>x.classList.toggle('current',x.dataset.stage===stage))}
function buildPacket(){const ask=$('prompt').value.trim();if(!ask){$('bridgeStatus').textContent='Écris d’abord ta demande';return}const project=getProject();const mastery=getMastery();const current=DATA.competencies.map(c=>({id:c.id,name:c.name,score:scoreFor(mastery[c.id]||stateFor(c.id)),evidence:(mastery[c.id]||{}).evidence||''}));$('packetOutput').value=`Tu travailles avec moi dans Engineer Method OS V3.\n\nOBJECTIF\nM'aider à construire une fonctionnalité logicielle tout en m'expliquant et en évaluant les compétences de mes 4 certificats IBM. Je suis débutant en programmation : guide-moi pas à pas.\n\nPROJET ACTIF\n${JSON.stringify(project,null,2)}\n\nMA DEMANDE\n${ask}\n\nRÈGLE DE MAÎTRISE\nNe considère jamais un certificat terminé comme preuve de maîtrise. Utilise la boucle : comprendre → expliquer → pratiquer → construire → tester → corriger → prouver.\n\nMES 14 BLOCS ET SCORES ACTUELS\n${JSON.stringify(current,null,2)}\n\nCERTIFICATS\n${DATA.certificates.map(c=>'- '+c.name+' : '+c.courses.join('; ')).join('\n')}\n\nÀ FAIRE\n1. Analyse le besoin avant de coder.\n2. Sélectionne seulement les compétences IBM réellement utiles.\n3. Pour chacune : certificat, cours, concept, pourquoi maintenant.\n4. Donne un petit exercice adapté à mon niveau actuel.\n5. Définis des critères d'acceptation et les tests.\n6. Indique quelle preuve GitHub ou projet démontrera la compétence.\n7. Si une information manque, écris UNKNOWN au lieu d'inventer.\n\nÀ LA FIN, ajoute exactement ce bloc JSON sans markdown autour :\n<ENGINEER_METHOD_UPDATE>\n{\n  "projectUpdate":{"name":"","problem":"","users":"","mvp":"","currentStep":""},\n  "skills":[{"block":"Bloc N","skill":"","certificate":"","course":"","why":"","exercise":"","proof":""}],\n  "stage":"specification|architecture|code|tests|github|publish"\n}\n</ENGINEER_METHOD_UPDATE>`;$('packetSection').classList.remove('hidden');$('bridgeStatus').textContent='Paquet prêt'}
function importResponse(){const text=$('importResponse').value.trim();const match=text.match(/<ENGINEER_METHOD_UPDATE>\s*([\s\S]*?)\s*<\/ENGINEER_METHOD_UPDATE>/);if(!match){$('importStatus').textContent='Bloc de mise à jour introuvable';return}try{const d=JSON.parse(match[1]);if(d.projectUpdate){const p=getProject();Object.entries(d.projectUpdate).forEach(([k,v])=>{if(k in p&&typeof v==='string'&&v.trim())p[k]=v.trim()});setProject(p);saveProject()}if(d.stage)setStage(d.stage);if(Array.isArray(d.skills)&&d.skills[0]){const first=d.skills[0];const matchSkill=DATA.competencies.find(c=>first.skill&&c.name.toLowerCase().includes(first.skill.toLowerCase().split(' ')[0]));if(matchSkill){selectedCompetency=matchSkill.id;renderMastery()}}$('importStatus').textContent='Importé avec succès'}catch{$('importStatus').textContent='JSON invalide'}}
function setupWorkshop(){$('saveProject').onclick=saveProject;$('resetProject').onclick=()=>{localStorage.removeItem(PROJECT_KEY);setProject({name:'Nouveau projet',problem:'',users:'',mvp:'',currentStep:'Définition du problème'});setStage('specification')};$('prepareButton').onclick=buildPacket;$('copyPacket').onclick=async()=>{try{await navigator.clipboard.writeText($('packetOutput').value);$('bridgeStatus').textContent='Copié — colle-le dans ChatGPT'}catch{$('bridgeStatus').textContent='Copie manuelle nécessaire'}};$('importButton').onclick=importResponse;loadProject()}
async function init(){try{const r=await fetch(DATA_URL);DATA=await r.json();setupTabs();renderStats();renderCertificates();renderSimilarity();renderSpecialties();renderRoadmap();renderGlobal();renderMastery();setupWorkshop()}catch(e){document.body.innerHTML=`<main class="shell"><section class="panel padded"><h1>Erreur de chargement</h1><p>${esc(e.message)}</p></section></main>`}}
init();